Complete rewrite in C only.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -5,24 +5,17 @@
 ###############################################################################
 
 SUBDIRS="`/bin/ls -F | grep / | awk -F/ '{print $1}' | xargs`"
+PKGS="libxbps"
+
 PREFIX=/usr/local
-DEFS="-D_FORTIFY_SOURCE=1 -D_XOPEN_SOURCE=700"
-WARN="-Wstack-protector"
-PKGS="glib-2.0 gobject-2.0 gthread-2.0 gio-2.0 gee-1.0 libxbps"
+PREFIX=${PREFIX}/etc
 CFLAGS="${CFLAGS}"
 LDFLAGS="${LDFLAGS}"
-VPKGS=
 PKG_CFLAGS=
 PKG_LDFLAGS=
 
 test ${CFLAGS} || CFLAGS="-O2 -pipe -mtune=generic"
 test ${LDFLAGS} || LDFLAGS="-Wl,--as-needed"
-
-CFLAGS="${CFLAGS} -fstack-protector -fPIC"
-
-for d in ${SUBDIRS}; do
-	CFLAGS="${CFLAGS} -I../${d}"
-done
 
 ###############################################################################
 # helper funcs.
@@ -54,61 +47,12 @@ check_pkg() {
 	fi
 }
 
-gen_vala() {
-	local name=${1}
-	local _common
-	[ "${name}" = "common" ] &&  _common="" ||  _common="--pkg=common"
-	printf "Generating sources for '%s'... " ${subdir}
-	valac --library=${name} -C -H ${name}/${name}.h --use-header=${name}.h \
-		-b ${name} -d ${name} --vapidir=common --includedir=. ${VPKGS} \
-		${_common} ${VFLAGS} ${name}/*.vala
-	[ $? -eq 0 ] || exit 1
-	printf "done.\n"
-}
-
 gen_make_var() {
 	local var=${1}
 	local val=${2}
 	local name=${3}
 	test ${name} && dir="${name}/" || dir=""
 	printf "${var} += ${val}\n" >> ${dir}Makefile
-}
-
-gen_subdir_makefile() {
-	local name=${1}
-	printf "Generating '${name}/Makefile'... "
-	sed -e "s|@PREFIX@|${PREFIX}|g" Makefile.in > ${name}/Makefile
-	gen_make_var "DEFS"    "${DEFS}"        "${name}"
-	gen_make_var "WARN"    "${WARN}"        "${name}"
-	gen_make_var "CFLAGS"  "${CFLAGS}"      "${name}"
-	gen_make_var "CFLAGS"  "\$(WARN)"       "${name}"
-	gen_make_var "CFLAGS"  "\$(DEFS)"       "${name}"
-	gen_make_var "CFLAGS"  "${PKG_CFLAGS}"  "${name}"
-	gen_make_var "LDFLAGS" "${PKG_LDFLAGS}" "${name}"
-	gen_make_var "LDFLAGS" "${LDFLAGS}"     "${name}"
-	gen_make_var "NAME"    "${name}"        "${name}"
-	printf "include rules.mk\n" >> ${name}/Makefile
-	printf "done.\n"
-}
-
-gen_main_make_rules() {
-	local targets="all install uninstall clean distclean"
-	for t in ${targets}; do
-		printf "${t}:\n" >> Makefile
-		printf "\t+@for d in \$(SUBDIRS); do " >> Makefile
-		printf "make -C \$\$d ${t}; " >> Makefile
-		printf "done\n" >> Makefile
-	done
-	printf "\trm -f Makefile\n\n" >> Makefile
-	printf ".PHONY: ${targets}\n\n" >> Makefile
-}
-
-gen_main_makefile() {
-	printf "Generating 'Makefile'... "
-	sed -e "s|@PREFIX@|${PREFIX}|g" Makefile.in > Makefile
-	gen_make_var "SUBDIRS" "${SUBDIRS}"
-	gen_main_make_rules
-	printf "done.\n"
 }
 
 ###############################################################################
@@ -121,12 +65,20 @@ for arg in $*; do
 		printf "Usage $0 [options]\n"
 		printf "  --help		(this message)\n"
 		printf "  --prefix=PREFIX	[default=/usr/local]\n"
+		printf "  --etcdir=ETCDIR	[default=PREFIX/etc]\n"
 		exit 0
 		;;
 	--prefix=*)
 		PREFIX=`get_option ${arg} prefix`
 		test ${PREFIX} || {
 			printf "Can't have an empty prefix!\n"
+			exit 1
+		}
+		;;
+	--etcdir=*)
+		ETCDIR=`get_option ${arg} etcdir`
+		test ${ETCDIR} || {
+			printf "Can't have an empty etcdir!\n"
 			exit 1
 		}
 		;;
@@ -138,22 +90,22 @@ for arg in $*; do
 done
 
 check_program install | grep -m1 -E "\."
+check_program flex
+check_program bison | grep -m1 -E "\."
 check_program pkg-config
-check_program valac
 
-for pkg in ${PKGS}; do
-	check_pkg ${pkg}
-	[ ! "${pkg}" = "gthread-2.0" ] && VPKGS="${VPKGS} --pkg=${pkg}"
-done
-
-VPKGS="${VPKGS} --pkg=posix --pkg=libxbps"
+for pkg in ${PKGS}; do check_pkg ${pkg} ; done
 
 PKG_CFLAGS="${PKG_CFLAGS} `pkg-config --cflags ${PKGS}`"
 PKG_LDFLAGS="${PKG_LDFLAGS} `pkg-config --libs ${PKGS}`"
 
-for subdir in ${SUBDIRS}; do
-	gen_vala ${subdir}
-	gen_subdir_makefile ${subdir}
-done
+printf "Generating 'Makefile'... "
+sed -e "s|@PREFIX@|${PREFIX}|g" Makefile.in > Makefile
+for d in ${SUBDIRS}; do gen_make_var "CFLAGS" "-I${d}" ; done
+gen_make_var "CFLAGS" "-DETCDIR=\\\"\\\\\"${ETCDIR}\\\\\"\\\""
+gen_make_var "CFLAGS" "${PKG_CFLAGS}"
+gen_make_var "LDFLAGS" "${PKG_LDFLAGS}"
+gen_make_var "TARGET" "xbps-repo-checkvers"
+sed -e "s|@PREFIX@|${PREFIX}|g" rules.mk.in >> Makefile
+printf "done.\n"
 
-gen_main_makefile
